apiVersion: apps/v1

kind: Deployment

metadata:
  labels:
    run: httpdd3
  name: httpdd3

spec:
  replicas: 2

  selector:
    matchLabels:
      run: httpdd3

  template:
    metadata:
      labels:
        run: httpdd3

    spec:
      containers:
        - image: gcr.io/searce-playground-v1/gcr77-test

          name: gcr77-test

          ports:
          - containerPort: 80
---
kind: Service

apiVersion: v1

metadata:
  name: httpdd3

spec:
  selector:
    run: httpdd3

  ports:
    - protocol: TCP

      port: 80

      targetPort: 80

  type: LoadBalancer
