apiVersion: skaffold/v2beta7
kind: Config
build:
  tagPolicy:
    sha256: {}
  artifacts:
    - image: priyanka-php-apache
      context: priyanka-php-apche
  googleCloudBuild:
    projectId: searce-playground-v1
deploy:
  kubectl:
    manifests:
      - k8.yaml
