apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo-clouddeploy
description: web-app delivery pipeline
serialPipeline:
 stages:
 - targetId: test
 - targetId: staging
